apm-server:
  host: "apm_server_container:8200"
  rum:
    enabled: true
    allow_origins: ["*"]
    allow_headers: ["Authorization"]

auth:
  secret_token: ""

output.elasticsearch:
  hosts: "http://elasticsearch_container:9200"
  enabled: true
  protocol: "http"
  username: "elastic"
  password: "ms_admin"
  ssl.enabled: false

monitoring.enabled: true

monitoring.elasticsearch:
  protocol: "http"
  username: "elastic"
  password: "ms_admin"
  hosts: "http://elasticsearch_container:9200"
