# docker compose -f docker-compose-volumes.yaml -f docker-compose-monitoring.yaml -f docker-compose-services.yaml up -d gateway notifications auth
version: "3.9"
networks:
  services_net:
  volumes_net:
  elastic_net:


services:
  gateway:
    container_name: gateway_container
    build:
      context: ./ms/p00-gateway-service
      dockerfile: Dockerfile.dev
    restart: always
    env_file: ./ms/p00-gateway-service/.env.dev
    environment:
      # overwrite env_file
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:3000
      - ELASTIC_SEARCH_URL=http://elastic:ms_admin@elasticsearch_container:9200
      - REDIS_HOST=redis://localhost:6379
      - AUTH_BASE_URL=http://localhost:4002
      - ENABLE_APM=1
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    ports:
      - 4000:4000
    networks:
      - services_net
      - volumes_net
      - elastic_net
    depends_on:
      - elasticsearch

  notifications:
    container_name: notification_container
    build:
      context: ./ms/p01-notification-service
      dockerfile: Dockerfile.dev
    restart: always
    env_file: ./ms/p01-notification-service/.env.dev
    environment:
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:3000
      - RABBITMQ_ENDPOINT=amqp://ms_admin:ms_admin@rabbitmq_container:5672
      - ELASTIC_SEARCH_URL=http://elastic:ms_admin@elasticsearch_container:9200
      - ENABLE_APM=1
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
      - EMAIL_HOST=smtp.ethereal.email
      - SENDER_EMAIL=kendrick.daniel@ethereal.email
      - SENDER_EMAIL_PASSWORD=5U21amcv3RSjAdCzBW
    ports:
      - 4001:4001
    networks:
      - services_net
      - volumes_net
      - elastic_net
    depends_on:
      - elasticsearch

  auth:
    container_name: auth_container
    build:
      context: ./ms/p02-auth-service
      dockerfile: Dockerfile.dev
    restart: always
    env_file: ./ms/p02-auth-service/.env.dev
    environment:
      - NODE_ENV=development
      - AP_GATEWAY_URL=http://localhost:4000
      - RABBITMQ_ENDPOINT=amqp://ms_admin:ms_admin@rabbitmq_container:5672
      - MYSQL_DB=mysql://ms_admin:ms_admin@mysql_container:3306/ms_auth
      - ELASTIC_SEARCH_URL=http://elastic:ms_admin@elasticsearch_container:9200
      - ENABLE_APM=1
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    ports:
      - 4002:4002
    networks:
      - services_net
      - volumes_net
      - elastic_net
    depends_on:
      - elasticsearch
      - mysql
