#https://www.elastic.co/guide/en/beats/heartbeat/current/monitor-http-options.html
heartbeat.config.monitors:
  path: ${path.config}/monitors.d/*.yml
  reload.enabled: false
  reload.period: 5s

heartbeat.monitors:
  - type: http
    id: ms-api-gateway
    name: FreelanPo API Gateway Service
    schedule: "@every 5s"
    hosts: ["http://gateway_container:4000/gateway-health"]
    check.request.method: GET
    check.response.status: [200]

  - type: http
    id: ms-notification
    name: FreelanPo Notification Service
    schedule: "@every 5s"
    hosts: ["http://notification_container:4001/notification-health"]
    check.request.method: GET
    check.response.status: [200]

  - type: http
    id: ms-auth
    name: FreelanPo Auth Service
    schedule: "@every 5s"
    hosts: ["http://auth_container:4002/auth-health"]
    check.request.method: GET
    check.response.status: [200]

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

monitoring.enabled: true

output.elasticsearch:
  hosts: ["http://elasticsearch_container:9200"]
  username: "elastic"
  password: "ms_admin"
