apiVersion: v1
kind: Service
metadata:
  name: ms-rrts-at-redis
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: ms-rrts-at-redis
  ports:
  - name: ms-rrts-at-redis
    port: 6379
    targetPort: 6379