apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-rrts-at-auth
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-rrts-at-auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25% 
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: ms-rrts-at-auth
    spec:
      containers:
      - name: ms-rrts-at-auth
        image: gordonsdev/p02-auth-service:stable
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '0.5'
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 150Mi
        ports:
        - name: auth-port
          containerPort: 4002
        env:
          - name: ENABLE_APM
            value: '1'
          - name: NODE_ENV
            value: 'production'
          - name: ENV_GATEWAY_TOKEN
            valueFrom:
              secretKeyRef:
                name: ms-rrts-at-backend-secret
                key: env-gateway-token
          - name: JWT_TOKEN
            valueFrom:
              secretKeyRef:
                name: ms-rrts-at-backend-secret
                key: jwt-token
          - name: RABBITMQ_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: ms-rrts-at-backend-secret
                key: rabbitmq-endpoint
          - name: MYSQL_DB
            valueFrom:
              secretKeyRef:
                name: ms-rrts-at-backend-secret
                key: mysql-db
          - name: CLOUD_NAME
            valueFrom:
              secretKeyRef:
                name: ms-rrts-at-backend-secret
                key: cloud-name
          - name: CLOUD_API_KEY
            valueFrom:
              secretKeyRef:
                name: ms-rrts-at-backend-secret
                key: cloud-api-key
          - name: CLOUD_API_SECRET
            valueFrom:
              secretKeyRef:
                name: ms-rrts-at-backend-secret
                key: cloud-api-secret
          - name: CLIENT_URL
            value: 'https://localhost:3000'
          - name: API_GATEWAY_URL
            value: 'http://ms-rrts-at-gateway.production.svc.cluster.local:4000'
          - name: ELASTIC_SEARCH_URL
            valueFrom:
              secretKeyRef:
                name: ms-rrts-at-backend-secret
                key: elasticsearch-url
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: ms-rrts-at-backend-secret
                key:  elastic-apm-server-url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: ms-rrts-at-backend-secret
                key: elastic-apm-secret-token