apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-rrts-at-notification
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-rrts-at-notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25% 
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: ms-rrts-at-notification
    spec:
      containers:
      - name: ms-rrts-at-notification
        image: gordonsdev/p01-notification-service:stable
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '0.5'
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 150Mi
        ports:
        - name: notif-port
          containerPort: 4001
        env:
          - name: ENABLE_APM
            value: '1'
          - name: NODE_ENV
            value: 'production'
          - name: CLIENT_URL
            value: 'http://localhost:3000'
          - name: RABBITMQ_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: ms-rrts-at-backend-secret
                key: rabbitmq-endpoint
          - name: SENDER_EMAIL
            valueFrom:
              secretKeyRef:
                name: ms-rrts-at-backend-secret
                key: sender-email
          - name: SENDER_EMAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ms-rrts-at-backend-secret
                key: sender-email-password
          - name: ELASTIC_SEARCH_URL
            valueFrom:
              secretKeyRef:
                name: ms-rrts-at-backend-secret
                key: elasticsearch-url
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: ms-rrts-at-backend-secret
                key:  elastic-apm-server-url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: ms-rrts-at-backend-secret
                key: elastic-apm-secret-token