apiVersion: v1
kind: Service
metadata:
  name: ms-rrts-at-mysql
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: ms-rrts-at-mysql
  ports:
  - name: ms-rrts-at-mysql
    port: 3306
    targetPort: 3306