apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-rrts-at-queue
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-rrts-at-queue
  template:
    metadata:
      labels:
        app: ms-rrts-at-queue
    spec:
      containers:
      - name: ms-rrts-at-queue
        image: rabbitmq:3.13-rc-management-alpine
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: ms-rrts-at-backend-secret
              key: rabbitmq-user
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: ms-rrts-at-backend-secret
              key: rabbitmq-password
        resources:
          limits:
            memory: "1Gi"
            cpu: "0.5"
          requests:
            memory: 150Mi
            cpu: 100m
        ports:
        - name: queue
          containerPort: 5672
          protocol: TCP
        - name: mgmt
          containerPort: 15672
          protocol: TCP
        volumeMounts:
          - name: rabbittmq-local-storage
            mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbittmq-local-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pvc